// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe0Le9jBzBTnp82164IcX680jZg4VpEaM',
    appId: '1:589381681563:web:3bdfed83f27178500de13e',
    messagingSenderId: '589381681563',
    projectId: 'imc1-c17b1',
    authDomain: 'imc1-c17b1.firebaseapp.com',
    storageBucket: 'imc1-c17b1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8hhH6H9Ei39nKmzSpgxkSeVri2c1sS0Q',
    appId: '1:589381681563:android:fc29c131ec66c4f60de13e',
    messagingSenderId: '589381681563',
    projectId: 'imc1-c17b1',
    storageBucket: 'imc1-c17b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvsTeONo7m69OpM_Hj_5-IoLvF9EJhwWI',
    appId: '1:589381681563:ios:6efc2ff86cb946f00de13e',
    messagingSenderId: '589381681563',
    projectId: 'imc1-c17b1',
    storageBucket: 'imc1-c17b1.firebasestorage.app',
    iosBundleId: 'com.example.imcSecured',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvsTeONo7m69OpM_Hj_5-IoLvF9EJhwWI',
    appId: '1:589381681563:ios:6efc2ff86cb946f00de13e',
    messagingSenderId: '589381681563',
    projectId: 'imc1-c17b1',
    storageBucket: 'imc1-c17b1.firebasestorage.app',
    iosBundleId: 'com.example.imcSecured',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAe0Le9jBzBTnp82164IcX680jZg4VpEaM',
    appId: '1:589381681563:web:6e5ab5ce04afcc340de13e',
    messagingSenderId: '589381681563',
    projectId: 'imc1-c17b1',
    authDomain: 'imc1-c17b1.firebaseapp.com',
    storageBucket: 'imc1-c17b1.firebasestorage.app',
  );
}
